class Strings:
    def __init__(self, language):
        self.language = language

    def getRegionalizedString(self, index):
            stringPT = ['Heróis que devem ser mandados para casa carregados.',
                      'Colocando os heróis para dormir (seus vagabundos)',
                      'Barras verdes detectadas',
                      'Botoes detectados',
                      'Botoes com barra verde detectados',
                      'Clicando em',
                      'heróis',
                      'Houve muitos cliques em heróis, tente aumentar o go_to_work_btn threshold',
                      'Nenhum herói que deveria ser enviado para casa encontrado.',
                      'Heróis que devem ser enviados para casa encontrados.',
                      'Herói não está trabalhando, enviando para casa.',
                      'Herói está trabalhando, não será enviado para casa.',
                      'Herói já está na casa, ou a casa está cheia.',
                      'O bot irá colocar os bonecos para trabalhar!',
                      'Enviando heróis com a energia cheia para o trabalho',
                      'Enviando heróis com a energia verde para o trabalho',
                      'Enviando todos heróis para o trabalho',
                      '💪 Todo os heróis enviados para o trabalho',
                      'Heróis enviados para o trabalho',
                      'O bot irá atualizar a posição dos heróis aguarde!',
                      'Atualizando posição dos heróis',
                      'O bot irá logar, aguarde!',
                      'Checando se o jogo se desconectou',
                      'Muitas tentativas de login, atualizando',
                      'Botão de conexão da carteira encontrado, logando!',
                      'Preenchendo campo de usuário!',
                      'Preenchendo campo de senha!',
                      'Clicando no botão login!',
                      'Botão de conexão pela metamask, clicado!',
                      'O bot irá consultar seu baú, aguarde!',
                      'Consultando seu baú',
                      'Saldo não encontrado.',
                      '🚨 Seu baú na conta',
                      'O bot irá tirar screenshot das suas telas, aguarde!',
                      '🖥 Aqui vai como está sua tela na conta',
                      'O bot irá atualizar a página e tentará logar novamente, aguarde!',
                      'janelas com o nome Bombcrypto encontradas!',
                      'Bot encontrou',
                      'Contas.',
                      'É hora de faturar alguns BCoins!!!',
                      'Janela atual:',
                      'Completamos mais um mapa na conta',
                      'Parabéns temos',
                      '🎉🎉🎉 nova(s) jaula(s) no novo mapa, na conta',
                      '\n\n>>---> Nenhuma janela com o nome Bombcrypto encontrada!',
                      'verificando se o jogo desconectou',
                      'Jogo desconectado, tentando reconectar!',
                      'jogo ainda conectado, prosseguindo a próxima ação!']

            stringEN = ['Heroes who should be sent home loaded.',
                        'Putting the heroes to sleep (you bums)',
                        'Green bars detected',
                        'Green bar buttons detected',
                        'Clicking on',
                        'heroes',
                        'There were too many clicks on heroes, try to increase the go_to_work_btn threshold',
                        'No hero that should be sent home found.',
                        'Heroes that must be sent home found.',
                        'Hero is not working, sending home.',
                        'Hero is working, will not be sent home.',
                        'Hero is already in the house, or the house is full.',
                        'The bot will put the puppets to work!',
                        'Sending energetic heroes to work',
                        'Sending Green Energy Heroes to Work',
                        'Sending all heroes to work',
                        '💪 All Heroes Sent To Work',
                        'Heroes sent to work',
                        'The bot will update the position of the heroes wait!',
                        'Updating Heroes Position',
                        'The bot will log in, please wait!',
                        'Checking if the game has disconnected',
                        'Too many login attempts, updating',
                        'Wallet connection button found, logging in!',
                        'Filling in user field!',
                        'Filling in password field!',
                        'By clicking the login button!',
                        'Connect button via metamask, clicked!',
                        'The bot will consult your chest, wait!',
                        'Consulting your chest',
                        'Balance not found.',
                        '🚨 Your chest 🚀🚀🚀 on account',
                        'The bot will take screenshots of your screens, please wait!',
                        'Heres how your account screen looks',
                        'The bot will refresh the page and try to login again, please wait!',
                        'windows with name Bombcrypto found!',
                        'Bot initialized in',
                        'Accounts.',
                        'Its time to cash in some BCoins!!!',
                        'Current window:',
                        'We completed another map in the account',
                        'Congratulations we have',
                        'new jail(s) on new map 🎉🎉🎉, on account',
                        '\n\n>>---> No window named Bombcrypto found!',
                        'checking if the game has disconnected',
                        'Game disconnected, trying to reconnect!',
                        'game still connected, moving next action!']

            if self.language == "pt":
                return stringPT[index]
            elif self.language == "en":
                if len(stringEN) >= index:
                    return stringEN[index]
                else:
                    return stringPT[index]
